### ISSUE TITLE
after upgrading zeek & python getting error about lambda

### ISSUE THREAD

**Issue by tbernhardson** [J-Gras/add-json#4]
After upgrading to zeek 5.1.1-0 & python 3.8.2-0 on Ubuntu LTS 22.04, getting error:
error in /opt/zeek/share/zeek/site/packages/add-json/add-json.zeek, line 40: lambda uses outer identifiers without [] captures: Log::orig_path_func

I have verified that I am running the latest version of add-json

google hasn't helped, any ideas?

**Comment by J-Gras** [comment]
@tbernhardson, I somehow missed this issue. Sorry! I've pushed a fix to master. Hopefully this is still helpful.

**Comment by hilt86** [comment]
@J-Gras I installed the package using zkg from github but still getting : 

```
line 40: lambda uses outer identifiers without [] captures: Log::orig_path_func
```

using /opt/zeek/bin/zeek version 5.2.1

**Comment by hilt86** [comment]
nvm - I realised I need to specify the version tag like : 

```
zkg install --version master https://github.com/J-Gras/add-json.git
```
